Watching for file changes with StatReloader
D:\Projects\basic\basic\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\basic\basic\views.py", line 6, in home
    celery_test.delay()
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 575, in apply_async
    return app.send_task(
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 784, in send_task
    with self.producer_or_acquire(producer) as P:
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 919, in producer_or_acquire
    producer, self.producer_pool.acquire, block=True,
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 1303, in producer_pool
    return self.amqp.producer_pool
  File "D:\Projects\basic\env\lib\site-packages\celery\app\amqp.py", line 583, in producer_pool
    self.app.connection_for_write()]
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 816, in connection_for_write
    return self._connection(url or self.conf.broker_write_url, **kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 867, in _connection
    return self.amqp.Connection(
  File "D:\Projects\basic\env\lib\site-packages\kombu\connection.py", line 181, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 85, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 70, in resolve_transport
    return symbol_by_name(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\Sanjib\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\redis.py", line 262, in <module>
    class PrefixedStrictRedis(GlobalKeyPrefixMixin, redis.Redis):
AttributeError: 'NoneType' object has no attribute 'Redis'
"GET / HTTP/1.1" 500 181960
D:\Projects\basic\basic\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\basic\basic\views.py", line 6, in home
    celery_test.delay()
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 575, in apply_async
    return app.send_task(
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 784, in send_task
    with self.producer_or_acquire(producer) as P:
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 919, in producer_or_acquire
    producer, self.producer_pool.acquire, block=True,
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 1303, in producer_pool
    return self.amqp.producer_pool
  File "D:\Projects\basic\env\lib\site-packages\celery\app\amqp.py", line 583, in producer_pool
    self.app.connection_for_write()]
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 816, in connection_for_write
    return self._connection(url or self.conf.broker_write_url, **kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 867, in _connection
    return self.amqp.Connection(
  File "D:\Projects\basic\env\lib\site-packages\kombu\connection.py", line 181, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 85, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 70, in resolve_transport
    return symbol_by_name(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\Sanjib\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\redis.py", line 262, in <module>
    class PrefixedStrictRedis(GlobalKeyPrefixMixin, redis.Redis):
AttributeError: 'NoneType' object has no attribute 'Redis'
"GET / HTTP/1.1" 500 182013
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\basic\basic\views.py", line 6, in home
    celery_test.delay()
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 575, in apply_async
    return app.send_task(
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 784, in send_task
    with self.producer_or_acquire(producer) as P:
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 919, in producer_or_acquire
    producer, self.producer_pool.acquire, block=True,
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 1303, in producer_pool
    return self.amqp.producer_pool
  File "D:\Projects\basic\env\lib\site-packages\celery\app\amqp.py", line 583, in producer_pool
    self.app.connection_for_write()]
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 816, in connection_for_write
    return self._connection(url or self.conf.broker_write_url, **kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 867, in _connection
    return self.amqp.Connection(
  File "D:\Projects\basic\env\lib\site-packages\kombu\connection.py", line 181, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 85, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 70, in resolve_transport
    return symbol_by_name(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\Sanjib\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\redis.py", line 262, in <module>
    class PrefixedStrictRedis(GlobalKeyPrefixMixin, redis.Redis):
AttributeError: 'NoneType' object has no attribute 'Redis'
"GET / HTTP/1.1" 500 182013
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Projects\basic\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Projects\basic\basic\views.py", line 6, in home
    celery_test.delay()
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 425, in delay
    return self.apply_async(args, kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\task.py", line 575, in apply_async
    return app.send_task(
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 784, in send_task
    with self.producer_or_acquire(producer) as P:
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 919, in producer_or_acquire
    producer, self.producer_pool.acquire, block=True,
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 1303, in producer_pool
    return self.amqp.producer_pool
  File "D:\Projects\basic\env\lib\site-packages\celery\app\amqp.py", line 583, in producer_pool
    self.app.connection_for_write()]
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 816, in connection_for_write
    return self._connection(url or self.conf.broker_write_url, **kwargs)
  File "D:\Projects\basic\env\lib\site-packages\celery\app\base.py", line 867, in _connection
    return self.amqp.Connection(
  File "D:\Projects\basic\env\lib\site-packages\kombu\connection.py", line 181, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 85, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\__init__.py", line 70, in resolve_transport
    return symbol_by_name(transport)
  File "D:\Projects\basic\env\lib\site-packages\kombu\utils\imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "C:\Users\Sanjib\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Projects\basic\env\lib\site-packages\kombu\transport\redis.py", line 262, in <module>
    class PrefixedStrictRedis(GlobalKeyPrefixMixin, redis.Redis):
AttributeError: 'NoneType' object has no attribute 'Redis'
"GET / HTTP/1.1" 500 182013
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 5238
"GET /static/css/base.css HTTP/1.1" 304 0
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 5238
Not Found: /static/css/bootstrap.css
"GET /static/css/bootstrap.css HTTP/1.1" 404 5317
Not Found: /static/css/base.css
"GET /static/css/base.css HTTP/1.1" 404 5317
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5317
"GET /login/ HTTP/1.1" 200 6950
Not Found: /static/css/bootstrap.css
"GET /static/css/bootstrap.css HTTP/1.1" 404 5317
Not Found: /static/css/base.css
"GET /static/css/base.css HTTP/1.1" 404 5317
C:\Users\user\Documents\django-celery\basic\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /login/ HTTP/1.1" 200 6950
"GET /static/css/base.css HTTP/1.1" 200 2134
"GET /static/css/bootstrap.css HTTP/1.1" 200 173352
"GET /login/ HTTP/1.1" 200 6950
"GET /login/ HTTP/1.1" 200 6950
"GET /register/ HTTP/1.1" 200 7256
"POST /register/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 7089
"GET /static/css/bootstrap.css HTTP/1.1" 304 0
"GET /static/css/base.css HTTP/1.1" 304 0
"POST /login/ HTTP/1.1" 200 7077
"POST /login/ HTTP/1.1" 200 7077
"GET /login/ HTTP/1.1" 200 6950
"POST /login/ HTTP/1.1" 200 7077
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 5274
"GET /static/css/bootstrap.css HTTP/1.1" 304 0
"GET /static/css/base.css HTTP/1.1" 304 0
"GET /account/f337a5d2-1800-4562-97ca-0b4643f1198d/ HTTP/1.1" 200 8035
"GET /media/default/dummy_image.png HTTP/1.1" 200 3445
"GET /account_search/?userQuery=ss HTTP/1.1" 200 5721
"GET /account_search/?userQuery=ss HTTP/1.1" 200 5721
"GET /static/css/bootstrap.css HTTP/1.1" 304 0
"GET /static/css/base.css HTTP/1.1" 304 0
C:\Users\user\Documents\django-celery\basic\celery.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Documents\django-celery\basic\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /account_search/?userQuery=ss HTTP/1.1" 200 5721
"GET /static/css/base.css HTTP/1.1" 200 2134
"GET /static/css/bootstrap.css HTTP/1.1" 200 173352
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5551
"GET /celery-tracker HTTP/1.1" 301 0
"GET /celery-tracker/ HTTP/1.1" 200 3876
"GET /static/celery_tracker/css/dashboard.css HTTP/1.1" 200 1924
"GET /static/celery_tracker/js/dashboard.js HTTP/1.1" 200 4926
"GET /static/admin/css/base.css HTTP/1.1" 200 19513
"GET /static/admin/css/forms.css HTTP/1.1" 200 8804
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/celery_tracker/fonts/icomoon.ttf HTTP/1.1" 200 1408
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /celery-tracker/timeline-data/?date=2022-04-27T00%3A00%3A00%2B03%3A00 HTTP/1.1" 200 2
"GET /admin/ HTTP/1.1" 200 9404
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
"GET /admin/logout/ HTTP/1.1" 200 1529
"GET /celery-tracker/ HTTP/1.1" 302 0
"GET /admin/login/?next=/celery-tracker/ HTTP/1.1" 200 2228
"GET /static/admin/css/login.css HTTP/1.1" 200 939
"POST /admin/login/?next=/celery-tracker/ HTTP/1.1" 302 0
"GET /celery-tracker/ HTTP/1.1" 200 3876
"GET /static/celery_tracker/css/dashboard.css HTTP/1.1" 304 0
"GET /static/celery_tracker/js/dashboard.js HTTP/1.1" 304 0
"GET /static/celery_tracker/fonts/icomoon.ttf HTTP/1.1" 304 0
"GET /celery-tracker/timeline-data/?date=2022-04-27T00%3A00%3A00%2B03%3A00 HTTP/1.1" 200 2
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\user\Documents\django-celery\contact_form\tasks.py changed, reloading.
Watching for file changes with StatReloader
"GET /celery-tracker/ HTTP/1.1" 200 3876
"GET /static/admin/css/base.css HTTP/1.1" 200 19513
"GET /static/celery_tracker/css/dashboard.css HTTP/1.1" 200 1924
"GET /static/celery_tracker/js/dashboard.js HTTP/1.1" 200 4926
"GET /static/admin/css/forms.css HTTP/1.1" 200 8804
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5659
"GET /contact HTTP/1.1" 301 0
"GET /contact/ HTTP/1.1" 200 922
Watching for file changes with StatReloader
"GET /contact/ HTTP/1.1" 200 922
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5659
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 5960
- Broken pipe from ('127.0.0.1', 50161)

"GET / HTTP/1.1" 200 5960
"GET /static/css/base.css HTTP/1.1" 200 2134
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5603
"GET / HTTP/1.1" 200 5960
"GET /login/ HTTP/1.1" 200 7286
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\Documents\django-celery\account\views.py", line 52, in login_view
    return redirect('home')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 130, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST /login/ HTTP/1.1" 500 85911
C:\Users\user\Documents\django-celery\django_celery_tracker\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\user\Documents\django-celery\account\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing or incorrect.): /login/
"POST /login/ HTTP/1.1" 403 2519
"GET /login/ HTTP/1.1" 200 7286
"POST /login/ HTTP/1.1" 200 7413
Internal Server Error: /login/
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\Documents\django-celery\account\views.py", line 52, in login_view
    return redirect('home')
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 41, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 130, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST /login/ HTTP/1.1" 500 85911
C:\Users\user\Documents\django-celery\account\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing or incorrect.): /login/
"POST /login/ HTTP/1.1" 403 2519
"GET /login/ HTTP/1.1" 200 7286
"POST /login/ HTTP/1.1" 302 0
"GET /celery-tracker/ HTTP/1.1" 200 3805
"GET /static/celery_tracker/js/dashboard.js HTTP/1.1" 200 4926
"GET /static/celery_tracker/css/dashboard.css HTTP/1.1" 200 1924
"GET /static/admin/css/forms.css HTTP/1.1" 200 8804
"GET /static/admin/css/base.css HTTP/1.1" 200 19513
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
"GET /static/celery_tracker/fonts/icomoon.ttf HTTP/1.1" 200 1408
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /celery-tracker/timeline-data/?date=2022-04-28T00%3A00%3A00%2B03%3A00 HTTP/1.1" 200 2
"GET /admin/ HTTP/1.1" 200 10119
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
C:\Users\user\Documents\django-celery\django_celery_tracker\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 10600
"GET /admin/django_celery_tracker/textform/ HTTP/1.1" 200 11225
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 5698
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
"GET /static/admin/js/actions.js HTTP/1.1" 200 7664
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/django_celery_tracker/textform/1/change/ HTTP/1.1" 200 11002
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /admin/django_celery_tracker/textform/ HTTP/1.1" 200 11225
C:\Users\user\Documents\django-celery\django_celery_tracker\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 5960
"GET /login/ HTTP/1.1" 200 7286
"POST /login/ HTTP/1.1" 302 0
"GET /celery-tracker/ HTTP/1.1" 200 3805
"GET /celery-tracker/timeline-data/?date=2022-04-28T00%3A00%3A00%2B03%3A00 HTTP/1.1" 200 2
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "C:\Users\user\Documents\django-celery\django_celery_tracker\views.py", line 28, in get_context_data
    context['celery_track'] = CeleryTask.objects.all()
NameError: name 'context' is not defined
"GET / HTTP/1.1" 500 78697
C:\Users\user\Documents\django-celery\django_celery_tracker\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7754
"GET / HTTP/1.1" 200 7719
"GET / HTTP/1.1" 200 7742
"GET / HTTP/1.1" 200 7722
"GET / HTTP/1.1" 200 6713
"GET / HTTP/1.1" 200 6698
"GET / HTTP/1.1" 200 6698
"GET / HTTP/1.1" 200 6698
"GET / HTTP/1.1" 200 7312
C:\Users\user\Documents\django-celery\django_celery_tracker\models.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7330
"GET /static/css/base.css HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 7948
"GET / HTTP/1.1" 200 7954
"GET / HTTP/1.1" 200 7963
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'task.args[0]'
"GET / HTTP/1.1" 500 180276
"GET / HTTP/1.1" 200 7954
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 8107
"GET /static/css/base.css HTTP/1.1" 200 2134
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5689
"GET / HTTP/1.1" 200 8107
"GET /account/ff0bac09-5e45-4860-9257-203ed4c41d4a/ HTTP/1.1" 200 7990
"GET /media/default/dummy_image.png HTTP/1.1" 200 3445
"GET / HTTP/1.1" 200 8107
"GET /admin/django_celery_tracker/celerytask/1 HTTP/1.1" 301 0
"GET /admin/django_celery_tracker/celerytask/1/ HTTP/1.1" 302 0
"GET /admin/django_celery_tracker/celerytask/1/change/ HTTP/1.1" 200 15795
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/css/base.css HTTP/1.1" 200 19513
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
"GET /static/admin/css/forms.css HTTP/1.1" 200 8804
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
"GET /static/admin/js/core.js HTTP/1.1" 200 5698
"GET /static/admin/js/actions.js HTTP/1.1" 200 7664
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET / HTTP/1.1" 200 8107
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 8107
"GET /static/css/base.css HTTP/1.1" 200 2134
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5689
Not Found: /api
"GET /api HTTP/1.1" 404 5665
Not Found: /api/
"GET /api/ HTTP/1.1" 404 7829
Unauthorized: /api/account/
"GET /api/account/ HTTP/1.1" 401 9965
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Watching for file changes with StatReloader
Unauthorized: /api/account/
"GET /api/account/ HTTP/1.1" 401 9965
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
"GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 5689
